version: '3.8'

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    hostname: ${MONGO_HOST}
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo1_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    hostname: ${MONGO_HOST}
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo2_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    hostname: ${MONGO_HOST}
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo3_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
